### ISSUE TITLE
Allow multiple e-mail addresses

### ISSUE THREAD

**Issue by leouieda** [pinga-lab/website#14]

**Comment by birocoles** [comment]
@leouieda, I have tried to change the .md file of my page in order to include a second email option. I have tried to replace "email" by "email (primary)" and "email (secondary)". It did not work, though. Do you have any idea about it?

**Comment by leouieda** [comment]
@birocoles done! Merge this into your branch for #29 and you can add the extra email as `email2: meh@on.br`.
