### ISSUE TITLE
Page for thesis

### ISSUE THREAD

**Issue by leouieda** [pinga-lab/website#15]
Make a page for defended thesis, like the one for papers. Link them to People pages.

**Comment by birocoles** [comment]
@leouieda, we could save the defended theses into the folder pdf or send them to figshare/zenodo and use the doi link. What do you think about it?

**Comment by leouieda** [comment]
@birocoles we can have both options. If people don't want to put it on figshare, they can upload a PDF to the `pdf` folder. If there is a DOI, provide that it should work.

For example, my Masters thesis is basically the paper, so there is no point in putting it on figshare.

**Comment by leouieda** [comment]
Done in #32
