### ISSUE TITLE
Page for Leo Vital

### ISSUE THREAD

**Issue by leouieda** [pinga-lab/website#20]
Criar a página do @leobvital no site.

cc @birocoles

**Comment by birocoles** [comment]
@leobvital, leia as instruções do [README](https://github.com/pinga-lab/website/blob/master/README.md) e tente criar a sua página.

**Comment by leobvital** [comment]
criei meu perfil e fiz um pull request lá.

2017-04-05 22:57 GMT-03:00 Vanderlei C Oliveira Jr <notifications@github.com
